### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by hebelsan** [gardener/gardener-extension-provider-azure#1141]
**How to categorize this issue?**

/area documentation
/kind enhancement
/platform azure

**What would you like to be added**:
The documentation in `usage.md`  states that the `networks.natGateway` section  is only available for zonal clusters `.zoned=true`.
See: https://github.com/gardener/gardener-extension-provider-azure/blob/543b98fe072596e03e07677c17a93aa2d8092646/docs/usage/usage.md?plain=1#L167

However I was able to use it with the following infraConf:
```
  infrastructureConfig:
    apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureConfig
    networks:
      vnet:
        name: Test-i540852
        resourceGroup: i540852-test
      workers: 10.0.0.128/25
      natGateway:
        enabled: true
        idleConnectionTimeoutMinutes: 4
        zone: 2
    zoned: false
```
