### ISSUE TITLE
NatGateway configurable idle connection timeout

### ISSUE THREAD

**Issue by dkistner** [gardener/gardener-extension-provider-azure#134]
**How to categorize this issue?**
/kind enhancement
/priority normal
/platform azure

**What would you like to be added**:
Make the timeout for idle connections configurable for the NatGateway, see here: https://www.terraform.io/docs/providers/azurerm/r/nat_gateway.html#idle_timeout_in_minutes

The corresponding field in the infrastructure config could look like this:
```
apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureConfig
networks:
  ...
  natGateway:
    enabled: true
    idleConnectionTimoutMinutes: 99 # keep idle connections open for 99 minutes
```

**Why is this needed**:
The default idle connection timeout of four minutes is not always sufficient.
