### ISSUE TITLE
Deserialize extension resources (Infrastructure, etc.) using strict deseriazliation, including during validation

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extension-provider-azure#270]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority 3
/platform azure

**What would you like to be added**:

Extension resources such as `Infrastructure` should be deserialized using the so-called "strict mode" that was introduced recently. In this mode, deserialization fails if there is any data that is not part of the API definition.

**Why is this needed**:

We recently had the case where the infrastructure creation failed because the user did not indent `natGateway` properly in an infrastructure resource :

```yaml
kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
spec:
  provider:
    type: azure
    infrastructureConfig:
      kind: InfrastructureConfig
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      networks:
        ...
      natGateway: # <--- nat gateway should be under networks
        ...
```

Changing the deserialization as described would enable us to detect and report such mistakes earlier, e.g. when the Shoot resource is created / updated, rather than much later when the infrastructure creation fails.

We would like to introduce this first for azure, later for other providers as well.
