### ISSUE TITLE
Shoot with VMO (VMSS Flex) cannot be deleted when the underlying resource group is deleted

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-azure#360]
/area quality
/kind bug
/priority 3
/platform azure

**What happened**:
Shoot with VMO (VMSS Flex) cannot be deleted when the underlying resource group is deleted

**What you expected to happen**:
Shoot with VMO (VMSS Flex) to be deleted when the underlying resource group is deleted

**How to reproduce it (as minimally and precisely as possible)**:

1. Create Shoot with VMO (VMSS Flex)

2. Delete manually the underlying resource group

3. Make sure that the Worker deletion fails with:

```yaml
status:
    lastError:
      codes:
      - ERR_CONFIGURATION_PROBLEM
      description: 'Error deleting worker: failed to cleanup machine dependencies:
        compute.VirtualMachineScaleSetsClient#List: Failure responding to request:
        StatusCode=404 -- Original Error: autorest/azure: Service returned an error.
        Status=404 Code="ResourceGroupNotFound" Message="Resource group ''shoot--foo--bar'
        could not be found."'
```

**Anything else we need to know?**:
See also https://github.com/gardener/machine-controller-manager-provider-azure/issues/19

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.21.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
