### ISSUE TITLE
NAT Gateway Support

### ISSUE THREAD

**Issue by dkistner** [gardener/gardener-extension-provider-azure#43]
**What would you like to be added**:
Azure will offer soon a NAT service (currently in a private preview) and there are some scenarios when users could need a dedicated nat service e.g. whitelisting scenarios which require a stable ip(s) for egress connections initiated within the cluster.

Currently all egress traffic from a Gardener managed Azure cluster is routed via the cluster load balancer.

As the nat gateway will come with additional costs I would recommend to integrate it optionally and make it configurable for the users.

As the nat gateway require always to have at least one public ip assigned. I would propose to make it possible for users to pass their public ip address(es) or public ip address range(s) to the extension via `.spec.providerConfig.networks.natGateway.ipAddresses[] | .ipAddressRanges[]`. Only if both lists are empty the Gardener extension would create one public ip and assign it to the service.

```
spec:
  type: azure
  ...
  providerConfig:
    apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureConfig
    networks:
      natGateway:
        enabled: <true|false>
        ipAddresses:
        - name: my-ip-resource-name
          resourceGroup: my-ip-resource-group
        ipAddressRanges:
        - name: my-iprange-resource-name
          resourceGroup: my-iprange-resource-group
    ...
```

Later on when we go on with multiple Availability Set support we will probably need to make the nat gateway required. In this case the `.spec.providerConfig.networks.natGateway.enabled` need to be always `true`.

**Why is this needed**:
Support scenarios which require a dedicated nat service e.g. whitelisting scenarios.

**Status**
- [x] Step 1 – NatGateway integration with one public ip attached by Gardener (no bring your own ip for the NatGateway in the first step due to terraform-providers/terraform-provider-azurerm#6052) and only for zoned cluster → #50
- [x] Step 2 – Enable bring your own ip for zoned clusters (when terraform-providers/terraform-provider-azurerm#6052 is fixed an a new version of the azurerm Terraform provider is released) → #54 
- [x] ~Step 3 – Enable NatGateway for AvailabilitySet based/non zoned clusters, when Standard Load Balancer is integrated for non zoned clusters (larger effort, due to LoadBalancer migration etc.). This will probably will require to deploy the NatGateway mandatory/non optional in addition to the Standard LoadBalancer.~

cc @vlerenc, @AndreasBurger, @MSSedusch

**Comment by MSSedusch** [comment]
should we allow customers to define how many nat gateways to create and in which zone (and in which subnet)?
```
networks:
      natGateways:
      - name: nat1
        zone: 1
        ipAddresses:
        - name: my-ip-resource-name
          resourceGroup: my-ip-resource-group
        ipAddressRanges:
        - name: my-iprange-resource-name
          resourceGroup: my-iprange-resource-group
        subnet: subnet1
      - name: nat2
        zone: 2
        ipAddresses:
        - name: my-ip-resource-name
          resourceGroup: my-ip-resource-group
        ipAddressRanges:
        - name: my-iprange-resource-name
          resourceGroup: my-iprange-resource-group
        subnet: subnet2
```
