### ISSUE TITLE
MachhineClass is invalid: nodeTemplate.zone in body must be of type string: "null"

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-azure#476]
/area quality
/kind bug
/kind regression
/platform azure

**What happened**:
After https://github.com/gardener/gardener-extension-provider-azure/pull/417 Shoot fails to be created with:

```yaml
  lastOperation:
    description: 'Flow "Shoot cluster reconciliation" encountered task errors: [task
      "Waiting until shoot worker nodes have been reconciled" failed: Error while
      waiting for Worker shoot--foo--azure-local/azure-local to become ready:
      error during reconciliation: Error reconciling worker: failed to deploy the
      machine classes: failed to apply manifests: 1 error occurred: could not apply
      object of kind "MachineClass" "shoot--foo--azure-local/shoot--foo--azure-local-cpu-worker-7d27e":
      MachineClass.machine.sapcloud.io "shoot--foo--azure-local-cpu-worker-7d27e"
      is invalid: nodeTemplate.zone: Invalid value: "null": nodeTemplate.zone in body
      must be of type string: "null"]'
```

**What you expected to happen**:
Shoot creation to work as expected.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a non-zoned cluster

```yaml
    infrastructureConfig:
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vnet:
          cidr: 10.222.0.0/16
        workers: 10.222.0.0/16
      zoned: false
```

2. Make sure that the creation fails with the above error.

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: e9c2d2b110b58082fe0aa3449c2f107b7d653a8f
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
