### ISSUE TITLE
`Bastion` controller does not respect `InfrastructureStatus`

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-provider-azure#485]
**How to categorize this issue?**

/area ops-productivity
/kind bug
/platform azure

**What happened**:
Creating a `Bastion` for a `Shoot` with a non-default `InfrastructureConfig` does not work.
It seems the `Bastion` controller does not respect the `InfrastructureStatus` and instead makes assumptions of how the infrastructure layout of the cluster: https://github.com/gardener/gardener-extension-provider-azure/blob/07ac30778838935cdf19a73b2e15467896cf58ab/pkg/controller/bastion/options.go

**What you expected to happen**:
Creation of the `Bastion` should succeed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a `Shoot` with

   ```yaml
   infrastructureConfig:
     apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
     kind: InfrastructureConfig
     networks:
       natGateway:
         enabled: true
       vnet:
         name: my-vnet
         resourceGroup: my-resource-group
       workers: 10.3.61.128/25
     zoned: true
   ```
2. Create a `Bastion` for this shoot cluster.
